### ISSUE TITLE
'Allow to set line width for LINESTRING' patch

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Komzpa/twms#8]
```
The patch adds ability to set line width for LINESTRING.

Please apply this patch to twms. Thanks.
```

Original issue reported on code.google.com by `maxstot...@gmail.com` on 14 Aug 2012 at 12:30

Attachments:
- [line_width.patch](https://storage.googleapis.com/google-code-attachments/twms/issue-8/comment-0/line_width.patch)

**Comment by andrewshadura** [comment]
@komzpa, how about merging this?

**Comment by Komzpa** [comment]
@andrewshadura no objections from my side.
